version: "2.2"

services:
  mysql-test-mil:
    image: mysql:5.7
    container_name: mysql-test-mil
    hostname: mysql-test-mil
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
       - "0.0.0.0:3306:3306"
    volumes:
    - ./script:/script
    - ./signals:/signals

  solr-test-mil:
    image: solr:7.5.0
    container_name: solr-test-mil
    hostname: solr-test-mil
    ports:
      - "0.0.0.0:8983:8983"
    volumes:
      - ./solr_cores/tag_user_view:/opt/solr/server/solr/tag_user_view
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - tag_user_view
      - /opt/solr/server/solr/tag_user_view
