version: "2.2"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
       - "0.0.0.0:3306:3306"

  solr:
    image: solr:7.5.0
    container_name: solr
    hostname: solr
    ports:
      - "0.0.0.0:8983:8983"
    volumes:
      - ./solr_cores/tag_user_view:/opt/solr/server/solr/tag_user_view
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - tag_user_view
      - /opt/solr/server/solr/tag_user_view
